ARG BASE_IMAGE=cardano-ignite-base
ARG TESTNET_BUILDER_IMAGE=scratch

FROM ${TESTNET_BUILDER_IMAGE} AS testnet_builder

#---------------------------------------------------------------------

FROM ${BASE_IMAGE} AS build

ARG CARDANO_NODE_VERSION="11.0.1"
ARG YACI_STORE_VERSION="2.0.2"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        unzip && \
    rm -rf /var/lib/apt/lists/*

# cardano-cli

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/cardano-node

RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/IntersectMBO/cardano-node/releases/download/${CARDANO_NODE_VERSION}/cardano-node-${CARDANO_NODE_VERSION}-linux-amd64.tar.gz \
        --output /usr/local/src/cardano-node/cardano-node-${CARDANO_NODE_VERSION}-linux-amd64.tar.gz
RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/IntersectMBO/cardano-node/releases/download/${CARDANO_NODE_VERSION}/cardano-node-${CARDANO_NODE_VERSION}-sha256sums.txt \
        --output /usr/local/src/cardano-node/cardano-node-${CARDANO_NODE_VERSION}-sha256sums.txt

WORKDIR /usr/local/src/cardano-node
RUN sha256sum --ignore-missing --check cardano-node-${CARDANO_NODE_VERSION}-sha256sums.txt

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/cardano-node/${CARDANO_NODE_VERSION}
RUN tar --extract --gzip --file=/usr/local/src/cardano-node/cardano-node-${CARDANO_NODE_VERSION}-linux-amd64.tar.gz --directory=/usr/local/src/cardano-node/${CARDANO_NODE_VERSION}
RUN chmod 0755 /usr/local/src/cardano-node/${CARDANO_NODE_VERSION}/bin/cardano-cli
RUN ln -snf /usr/local/src/cardano-node/${CARDANO_NODE_VERSION}/bin/cardano-cli /usr/local/bin/cardano-cli

# yaci-store

RUN install --directory --owner=root --group=root --mode=0755 /usr/local/src/yaci-store

RUN curl --proto '=https' --tlsv1.3 \
        --location https://github.com/bloxbean/yaci-store/releases/download/rel-native-${YACI_STORE_VERSION}/yaci-store-${YACI_STORE_VERSION}-linux-x64-all.zip \
        --output /usr/local/src/yaci-store/yaci-store-${YACI_STORE_VERSION}-linux-x64-all.zip

RUN unzip /usr/local/src/yaci-store/yaci-store-${YACI_STORE_VERSION}-linux-x64-all.zip -d /usr/local/src/yaci-store
RUN ln -snf /usr/local/src/yaci-store/yaci-store-${YACI_STORE_VERSION}/yaci-store /usr/local/bin/yaci-store

#---------------------------------------------------------------------

FROM ${BASE_IMAGE} AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        doas \
        postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# cardano-cli

COPY --from=build --chown=root:root /usr/local/bin/cardano-cli /usr/local/bin/cardano-cli

# user and group

RUN groupadd --gid 10000 cardano && \
    useradd --comment 'cardano' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 cardano

# yaci-store

RUN install --directory --owner=cardano --group=cardano --mode=0750 /opt/yaci && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/yaci/config

COPY --from=build --chown=root:root /usr/local/bin/yaci-store /opt/yaci/yaci-store
COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/pools/1/configs/alonzo-genesis.json /opt/yaci/config
COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/pools/1/configs/byron-genesis.json /opt/yaci/config
COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/pools/1/configs/conway-genesis.json /opt/yaci/config
COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/pools/1/configs/shelley-genesis.json /opt/yaci/config

# Permit cardano user to run commands 'ip' and 'tc' as root
RUN echo 'permit setenv { PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin } :cardano' >> /etc/doas.conf
RUN echo 'permit nopass cardano as root cmd ip' >> /etc/doas.conf
RUN echo 'permit nopass cardano as root cmd tc' >> /etc/doas.conf

COPY yaci-store/cmd.sh /
RUN chmod 0755 /cmd.sh

COPY scripts/node_routes.sh /
RUN chmod 0755 /node_routes.sh

COPY scripts/wait_on_tip.sh /
RUN chmod 0755 /wait_on_tip.sh

USER cardano

CMD ["/cmd.sh"]
