apiVersion: 1
datasources:
  - name: dbsync
    uid: dbsync_uid
    type: postgres
    url: db.example:5432
    user: dbsync
    secureJsonData:
      password: 'dbsync'
    jsonData:
      database: dbsync
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timescaledb: false

