apiVersion: 1
datasources:
  - name: sidecar
    uid: sidecar_uid
    type: postgres
    url: db.example:5432
    user: sidecar
    secureJsonData:
      password: 'sidecar'
    jsonData:
      database: sidecar
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timescaledb: false

