ARG BASE_IMAGE=cardano-ignite-base
ARG TESTNET_BUILDER_IMAGE=scratch
ARG HASKELL_BUILDER_IMAGE=scratch

FROM ${TESTNET_BUILDER_IMAGE} AS testnet_builder

#---------------------------------------------------------------------

FROM ${HASKELL_BUILDER_IMAGE} AS build

RUN apt update && \
    apt install -y --no-install-recommends \
        libclang-dev && \
    rm -rf /var/lib/apt/lists/*

# NOTE:
# Additional ARG definitions can be found further below in the Dockerfile.

# db-server

ARG DB_SERVER_REPO="https://github.com/pragma-org/db-server.git"
ARG DB_SERVER_REF="main"

WORKDIR /usr/local/src
RUN git init db-server

WORKDIR /usr/local/src/db-server
RUN git fetch --depth 1 ${DB_SERVER_REPO} ${DB_SERVER_REF} && \
    git checkout FETCH_HEAD && \
    git submodule update --init --recursive
RUN printf "package *\n\
  ghc-options: +RTS -A128m -n2m -RTS\n\
\n\
jobs: \$ncpus\n\
semaphore: True" > /usr/local/src/db-server/cabal.project.local

WORKDIR /usr/local/src/db-server

RUN cabal update && \
    cabal install exe:db-server --install-method=copy \
      --installdir=/usr/local/bin --overwrite-policy=always

RUN strip --strip-unneeded /usr/local/bin/db-server

# rustup

RUN curl --proto '=https' --tlsv1.3 -sSf https://sh.rustup.rs | sh -s -- -y

RUN ln -snf /root/.cargo/bin/cargo /usr/local/bin/cargo && \
    ln -snf /root/.cargo/bin/rustc /usr/local/bin/rustc

# amaru

ARG AMARU_REF="17020694ec00b39668dd0d9e87902f94e99590fa"
ARG AMARU_REPO="https://github.com/pragma-org/amaru.git"

WORKDIR /usr/local/src
RUN git init amaru

WORKDIR /usr/local/src/amaru
RUN git fetch --depth 1 ${AMARU_REPO} ${AMARU_REF} && \
    git checkout FETCH_HEAD && \
    git submodule update --init --recursive

RUN cargo build --release

RUN /usr/local/src/amaru/target/release/amaru --help

#---------------------------------------------------------------------

FROM ${BASE_IMAGE} AS main

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        doas \
        libstdc++6 \
        postgresql-client && \
    rm -rf /var/lib/apt/lists/*

# amaru

COPY --from=build --chown=root:root /usr/local/src/amaru/target/release/amaru /usr/local/bin/amaru

# libsodium

COPY --from=build --chown=root:root /usr/local/lib/libsodium.so /usr/local/lib
RUN ln -snf /usr/local/lib/libsodium.so /usr/local/lib/libsodium.so.23 && \
    ln -snf /usr/local/lib/libsodium.so /usr/local/lib/libsodium.so.23.3.0

# secp256k1

COPY --from=build --chown=root:root /usr/lib/libsecp256k1.so* /usr/local/lib/
RUN ldconfig

# db-server

COPY --from=build --chown=root:root /usr/local/bin/db-server /usr/local/bin/db-server

# user and group

RUN groupadd --gid 10000 cardano && \
    useradd --comment 'cardano' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 cardano

# cardano-node

RUN install --directory --owner=root --group=root --mode=0755 /opt/cardano-node && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/data && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/data/db && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/pools && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/amaru

COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/pools /opt/cardano-node/pools
COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/utxos /opt/cardano-node/utxos

RUN echo 'permit setenv { PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin } :cardano' >> /etc/doas.conf
RUN echo 'permit nopass cardano as root cmd ip' >> /etc/doas.conf
RUN echo 'permit nopass cardano as root cmd tc' >> /etc/doas.conf

COPY cardano-node/scripts/*.sh /
COPY scripts/node_routes.sh /
RUN chmod 0755 /*.sh

COPY amaru/cmd.sh /
RUN chmod 0755 /cmd.sh

USER cardano

CMD ["/cmd.sh"]
