{
 "title": "Default",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consensus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH latest_tips AS (\n    SELECT DISTINCT ON (pool_id) *\n    FROM node_tips \n    ORDER BY pool_id, updated_at DESC\n)\nSELECT CASE\n    WHEN COUNT(*) FILTER (WHERE pool_id = 'starting') > 0 THEN 'Generating Synthetic Chain'\n    WHEN COUNT(*) FILTER (WHERE hash IS NULL) > 0 THEN 'Degraded'\n    WHEN COUNT(DISTINCT hash) = 1 AND SUM(CASE WHEN hash IS NULL THEN 1 ELSE 0 END) = 0 \n        THEN 'Healthy'\n    ELSE 'Diverged' \nEND AS status\nFROM latest_tips;"
    }
   ]
  },
  {
   "title": "Cardano Node",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"http_ip4_basic\", instance=~\"http://p[0-9]+(bp|r[0-9])?.*\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 0, "y": 5 } },
  {
   "title": "CoreDNS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://ns.example:8090/health\"}) or on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_num_procs{groupname=\"grafana_consensus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://grafana.example:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cardano DB Sync",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://dbsync.example:8080\"}) or on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blockfrost",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://blockfrost.example:3000/health\"}) or on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yaci Store",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://yaci.example:8080/actuator/health\"}) or on() vector(-1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://prometheus.example:9090/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blackbox Exporter",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://blackbox.example:9115/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loki",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://loki.example:3100/metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grafana",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"http_ip4_basic\",instance=\"http://grafana.example:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 22, "y": 5 } },
  { "title": "Block Producer Tips", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n    pool_id,\n    block, \n    SUBSTRING(hash FROM 1 FOR 8) AS hash\nFROM node_tips;"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core Service",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "targets": [
      { "expr": "probe_duration_seconds", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node Exporter",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "namedprocess_namegroup_num_procs{groupname=\"node_exporter\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Process Exporter",
     "type": "state-timeline",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "namedprocess_namegroup_num_procs{groupname=\"process_exporte\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topology",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Physical Topology",
     "type": "nodeGraph",
     "gridPos": { "h": 26, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT \n  id,\n  title,\n  subtitle,\n  mainstat,\n  secondarystat,\n  color,\n  icon from ci_nodes"
      },
      {
       "rawSql": "SELECT \n  id,\n  source,\n  target from ci_edges ;"
      }
     ]
    },
    {
     "title": "Localroot Topology",
     "type": "nodeGraph",
     "gridPos": { "h": 26, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT \n  id,\n  title,\n  subtitle,\n  mainstat,\n  secondarystat,\n  color,\n  icon FROM ci_nodes WHERE id IN (SELECT source FROM cn_edges UNION SELECT target from cn_edges)"
      },
      {
       "rawSql": "SELECT \n  id,\n  source,\n  target from cn_edges ;"
      }
     ]
    }
   ]
  },
  { "title": "Cardano Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<h1></h1>\n<h3 style=\"text-align: left\">Block Chain</h3>"
   }
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{instance!~\"otlp.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{job=\"amaru\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{instance!~\"otlp.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{job=\"amaru\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{instance!~\"otlp.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "cardano_node_metrics_epoch_int{job=\"amaru\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_forks_counter",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{instance!~\"otlp.*\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "cardano_node_metrics_density_real{job=\"amaru\"}",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Chain Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT\n DATE_BIN('5 min',itime, '2000-1-1') AS time,\n AVG(rel_size) AS avg_rel_size,\n AVG(rel_mem) AS avg_rel_mem,\n AVG(rel_steps) AS avg_rel_steps\n FROM (\n SELECT\n MIN(b.time) AS itime,\n 1.0 * MIN(b.size) / MIN(p.max_block_size) AS rel_size,\n SUM(r.unit_mem) / MIN(p.max_block_ex_mem) AS rel_mem,\n SUM(r.unit_steps) / MIN(p.max_block_ex_steps) AS rel_steps\n FROM block b\n LEFT JOIN tx t\n ON b.id = t.block_id\n LEFT JOIN redeemer r\n ON t.id = r.tx_id\n LEFT JOIN epoch_param p\n ON b.epoch_no = p.epoch_no\n WHERE $__timeFilter(time)\n GROUP BY b.hash\n ) a                                        \n GROUP BY time\n ORDER BY time;"
    }
   ]
  },
  {
   "title": "TX Canaries Lost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select * from get_canary_loss();"
    }
   ]
  },
  {
   "title": "TX Monitoring Delay",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "rawSql": "select time,delay from get_canary_delay() where $__timeFilter(\"time\")"
    }
   ]
  },
  {
   "title": "TX 2 Blocks Acceptance Rate",
   "type": "gauge",
   "description": "Fraction of canary TXs accepted within 2 blocks.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select * from get_canary_percentage($__timeFrom(), $__timeTo())"
    }
   ]
  },
  {
   "title": "Logged Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (error) (count_over_time({container_name=~\"p[0-9]+(bp|r[0-9])?\"} | json | sev=\"Error\" | line_format \"{{.data.error}}\"[5m]))",
     "legendFormat": "Errors per 5min"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "<h1></h1>\n<h3 style=\"text-align: left\">Block Forging</h3>"
   }
  },
  {
   "title": "Blocks Rejected",
   "type": "timeseries",
   "description": "Since the last restart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_counter - cardano_node_metrics_Forge_adopted_counter",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Missed Slots",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissed_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Slot Leading Share",
   "type": "timeseries",
   "description": "percentage of slots led",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(cardano_node_metrics_Forge_node_is_leader_counter[1h])/rate(cardano_node_metrics_slotNum_int[1h]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "options": {
    "content": "<h1></h1>\n<h3 style=\"text-align: left\">Network</h3>"
   }
  },
  {
   "title": "One Second Block CDF",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfOne_real",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Three Second Block CDF",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfThree_real",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Five Second Block CDF",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_cdfFive_real",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Block Delay",
   "type": "timeseries",
   "description": "Milliseconds (ms)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_real*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Served Ratio",
   "type": "timeseries",
   "description": "Percentage of blocks on tip served to downstream peers",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_served_block_counter[1h])/rate(cardano_node_metrics_blockNum_int[1h])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hot Big Ledger Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_ActiveBigLedgerPeers_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound Warm Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_inboundGovernor_warm_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Inbound Hot Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_inboundGovernor_hot_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Outbound Hot Peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_peerSelection_Hot_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 82 },
   "options": {
    "content": "<h1></h1>\n<h3 style=\"text-align: left\">Transactions</h3>"
   }
  },
  {
   "title": "Transaction Rate",
   "type": "timeseries",
   "description": "Over 1 hour (h)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_txsProcessedNum_counter{instance!~\"otlp.*\"}[1h])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "rate(cardano_node_metrics_txsProcessedNum_counter{job=\"amaru\"}[1h])",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Transactions in Mempool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mempool Resync Duration",
   "type": "timeseries",
   "description": "Milliseconds (ms)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsSyncDuration_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mempool Bytes",
   "type": "timeseries",
   "description": "Bytes",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mempool Fullness",
   "type": "timeseries",
   "description": "mempool size / capacity. Capacity is published as a Prometheus recording rule mempool_capacity_bytes by scripts/prometheus_rules.sh: MempoolCapacityBytesOverride if set in testnet.yaml, else 2 * (maxBlockBodySize - fixedBlockBodyOverhead).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int / scalar(mempool_capacity_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 98 },
   "options": {
    "content": "<h1></h1>\n<h3 style=\"text-align: left\">Process</h3>"
   }
  },
  {
   "title": "Start Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_oldest_start_time_seconds{groupname=~\"cardano-node|amaru\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "namedprocess_namegroup_open_filedesc{groupname=~\"cardano-node|amaru\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Live Bytes",
   "type": "timeseries",
   "description": "Megabytes (MB)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_RTS_gcLiveBytes_int / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "description": "Over 1 hour (h)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "rate(rts_gc_num_gcs[1h])*3600", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Ingress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m])) by (instance) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Egress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m])) by (instance) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inter Continental Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device=~\"eunax0\", instance=\"nagw.example:9100\"}[5m])+rate(node_network_transmit_bytes_total{device=~\"eunax0\", instance=\"nagw.example:9100\"}[15m]))*8",
     "legendFormat": "EU - NA"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{device=~\"aseux0\", instance=\"eugw.example:9100\"}[5m])+rate(node_network_transmit_bytes_total{device=~\"aseux0\", instance=\"eugw.example:9100\"}[15m]))*8",
     "legendFormat": "AS - EU"
    },
    {
     "expr": "(rate(node_network_receive_bytes_total{device=~\"asnax0\", instance=\"nagw.example:9100\"}[5m])+rate(node_network_transmit_bytes_total{device=~\"asnax0\", instance=\"nagw.example:9100\"}[15m]))*8",
     "legendFormat": "AS - NA"
    }
   ]
  },
  {
   "title": "Ada Pots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 187 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n    CASE \n        WHEN NOT EXISTS (\n            SELECT 1\n            FROM ada_pots\n            GROUP BY epoch_no\n            HAVING NOT (\n                (COUNT(DISTINCT fees) = 0 OR (COUNT(DISTINCT fees) = 1 AND COUNT(fees) = COUNT(*)))\n                AND\n                (COUNT(DISTINCT treasury) = 0 OR (COUNT(DISTINCT treasury) = 1 AND COUNT(treasury) = COUNT(*)))\n                AND\n                (COUNT(DISTINCT reserves) = 0 OR (COUNT(DISTINCT reserves) = 1 AND COUNT(reserves) = COUNT(*)))\n            )\n        ) THEN 'Consensus'\n        ELSE 'Divergence'\n    END AS result;"
      }
     ]
    },
    {
     "title": "Cardano DB Sync",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 189 },
     "targets": [
      {
       "rawSql": "select epoch_no,fees,treasury,reserves from ada_pots where source='dbsync' order by epoch_no desc limit 5;"
      }
     ]
    },
    {
     "title": "Yaci Store",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 189 },
     "targets": [
      {
       "rawSql": "select epoch_no,fees,treasury,reserves from ada_pots where source='yaci' order by epoch_no desc limit 5;"
      }
     ]
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "description": "Per-container cardano-node CPU usage in cores (rate over 5m).",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(namedprocess_namegroup_cpu_seconds_total{groupname=\"cardano-node\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Pause Time",
   "type": "timeseries",
   "description": "Total GC pause time over the last 5 minutes (ms).",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(rts_gc_gc_wall_ms[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TX Acceptance Rate",
   "type": "timeseries",
   "description": "Fraction of submitted txs accepted by the node, 5m window.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_submissions_accepted_counter[5m]) / rate(cardano_node_metrics_submissions_submitted_counter[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}