---

x-base: &base
  image: ${testnet}:latest
  restart: unless-stopped
  logging:
    driver: "loki"
    options:
      mode: non-blocking
      loki-url: "http://127.0.0.1:3100/loki/api/v1/push"
      loki-retries: "5"
  build:
    context: "../../"
    dockerfile: "cardano-node/Dockerfile.source"
    args:
      CARDANO_NODE_REF: "87e2c9fc1a5f8bcc236aa9c14825c994181e6f19"

x-env: &env
  POOL_ID: "0" # Placeholder required for override
  SYSTEM_START: ${SYSTEM_START:-}

services:
  p1:
    <<: *base
    container_name: p1
    hostname: p1.example
    volumes:
      - p1:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "1"
      PEER_SHARING: "false"
      OUROBOROS_GENESIS: "true"
      UTXOHD: "true"

  p2:
    <<: *base
    container_name: p2
    hostname: p2.example
    volumes:
      - p2:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "2"
      PEER_SHARING: "false"

  p3:
    <<: *base
    container_name: p3
    hostname: p3.example
    volumes:
      - p3:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "3"
      PEER_SHARING: "false"
      OUROBOROS_GENESIS: "true"

  p4:
    <<: *base
    container_name: p4
    hostname: p4.example
    volumes:
      - p4:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "4"
      OUROBOROS_GENESIS: "true"
      UTXOHD: "true"

  p5:
    <<: *base
    container_name: p5
    hostname: p5.example
    volumes:
      - p5:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "5"
      OUROBOROS_GENESIS: "true"

  p6:
    <<: *base
    container_name: p6
    hostname: p6.example
    volumes:
      - p6:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "6"
      PEER_SHARING: "false"

  p7:
    <<: *base
    container_name: p7
    hostname: p7.example
    volumes:
      - p7:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "7"
      PEER_SHARING: "false"

  p8:
    <<: *base
    container_name: p8
    hostname: p8.example
    volumes:
      - p8:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "8"

  p9:
    <<: *base
    container_name: p9
    hostname: p9.example
    volumes:
      - p9:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "9"
      UTXOHD: "true"

  p10:
    <<: *base
    container_name: p10
    hostname: p10.example
    volumes:
      - p10:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "10"

  p11:
    <<: *base
    container_name: p11
    hostname: p11.example
    volumes:
      - p11:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "11"

  p12:
    <<: *base
    container_name: p12
    hostname: p12.example
    volumes:
      - p12:/opt/cardano-node/data
    environment:
      <<: *env
      POOL_ID: "12"

  # DNS Server
  ns:
    image: coredns/coredns:1.12.2
    container_name: ns
    hostname: ns.example
    restart: unless-stopped
    command: -conf /etc/coredns/corefile
    volumes:
      - ./coredns:/etc/coredns # Mount custom corefile

  sidecar:
    image: ${testnet}_sidecar:latest
    container_name: sidecar
    hostname: sidecar.example
    restart: unless-stopped
    environment:
      POOLS: "12"
    build:
      context: "../../"
      dockerfile: "sidecar/Dockerfile"

  # Client 1
  # Used by cardano-db-sync
  c1:
    <<: *base
    container_name: c1
    hostname: c1.example
    volumes:
      - c1:/opt/cardano-node
    environment:
      POOL_ID: "1"
      TYPE: "client"
      SYSTEM_START: ${SYSTEM_START:-}

  # TX generator 1
  c2:
    <<: *base_na
    container_name: c2
    hostname: c2.example
    volumes:
      - c2:/opt/cardano-node
    environment:
      POOL_ID: "1"
      TYPE: "txg"
      TPS: "1"
      UTXOHD: "true"
      SYSTEM_START: ${SYSTEM_START:-}

  # PostgreSQL Database
  db:
    image: postgresql:latest
    container_name: db
    hostname: db.example
    restart: unless-stopped
    volumes:
      - db:/opt/postgresql
    build:
      context: "../../"
      dockerfile: "postgresql/Dockerfile"

  dbsync:
    image: cardano-db-sync:latest
    container_name: dbsync
    hostname: dbsync.example
    restart: unless-stopped
    volumes:
      - dbsync:/opt/cardano-db-sync
      - c1:/opt/cardano-node
    environment:
      DB_HOST: "db.example"
    build:
      context: "../../"
      dockerfile: "cardano-db-sync/Dockerfile.binary"
    depends_on:
      db:
        condition: service_started

  blockfrost:
    image: blockfrost:latest
    container_name: blockfrost
    hostname: blockfrost.example
    restart: unless-stopped
    volumes:
      - c1:/opt/cardano-node
    environment:
      DB_HOST: "db.example"
    build:
      context: "../../"
      dockerfile: "blockfrost/Dockerfile"
    depends_on:
      dbsync:
        condition: service_started

  prometheus:
    image: prom/prometheus:v3.4.2
    container_name: prometheus
    hostname: prometheus.example
    restart: unless-stopped
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      blackbox:
        condition: service_started

  blackbox:
    image: quay.io/prometheus/blackbox-exporter:v0.27.0
    container_name: blackbox
    hostname: blackbox.example
    restart: unless-stopped
    command: --config.file=/etc/blackbox_exporter/blackbox.yml
    volumes:
      - ../../blackbox:/etc/blackbox_exporter/
    cap_add:
      - NET_ADMIN
      - NET_RAW

  loki:
    image: grafana/loki:3.4.4
    container_name: loki
    hostname: loki.example
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki:/loki

  grafana:
    image: grafana/grafana:12.0.2
    container_name: grafana
    hostname: grafana.example
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ../../grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_USER: cardano
      GF_SECURITY_ADMIN_PASSWORD: cardano

volumes:
  p1:
  p2:
  p3:
  p4:
  p5:
  p6:
  p7:
  p8:
  p9:
  p10:
  p11:
  p12:
  c1:
  c2:
  db:
  dbsync:
  prometheus:
  loki:
  grafana:
