#!/usr/bin/env bash

# Emit Prometheus recording rules with testnet-derived constants.
#
# Currently emits:
#   mempool_capacity_bytes
#     - MempoolCapacityBytesOverride if set in testnet.yaml
#     - else 2 * (maxBlockBodySize - fixedBlockBodyOverhead)
#       where fixedBlockBodyOverhead = 1024 (see
#       ouroboros-consensus-cardano/.../Shelley/Ledger/Mempool.hs)

set -o errexit
set -o pipefail

if [ $# -ne 1 ]; then
    echo "Usage: $0 <testnet.yaml>" >&2
    exit 1
fi

TESTNET_YAML="$1"

if [ ! -f "$TESTNET_YAML" ]; then
    echo "Error: $TESTNET_YAML not found" >&2
    exit 1
fi

FIXED_BLOCK_BODY_OVERHEAD=1024

# testnet.yaml is a multi-document YAML; the protocolParams and the
# node-config-override doc each live in their own document. Walk all docs
# and pick the first non-null value for each field.
MAX_BLOCK_BODY_SIZE="$(yq ea -N '[.. | .maxBlockBodySize? | select(. != null)] | .[0]' "$TESTNET_YAML")"
MEMPOOL_OVERRIDE="$(yq ea -N '[.. | .MempoolCapacityBytesOverride? | select(. != null)] | .[0]' "$TESTNET_YAML")"

if [ -z "$MAX_BLOCK_BODY_SIZE" ] || [ "$MAX_BLOCK_BODY_SIZE" = "null" ]; then
    echo "Error: maxBlockBodySize not found in $TESTNET_YAML" >&2
    exit 1
fi

if [ -n "$MEMPOOL_OVERRIDE" ] && [ "$MEMPOOL_OVERRIDE" != "null" ]; then
    MEMPOOL_CAPACITY_BYTES="$MEMPOOL_OVERRIDE"
    SOURCE="MempoolCapacityBytesOverride"
else
    MEMPOOL_CAPACITY_BYTES=$(( 2 * (MAX_BLOCK_BODY_SIZE - FIXED_BLOCK_BODY_OVERHEAD) ))
    SOURCE="2 * (${MAX_BLOCK_BODY_SIZE} - ${FIXED_BLOCK_BODY_OVERHEAD})"
fi

cat <<EOF
# Auto-generated by scripts/prometheus_rules.sh. Do not edit.
# Source: $(basename "$TESTNET_YAML")
groups:
  - name: testnet_constants
    rules:
      # mempool_capacity_bytes = ${SOURCE}
      - record: mempool_capacity_bytes
        expr: vector(${MEMPOOL_CAPACITY_BYTES})
EOF
