ARG BASE_IMAGE=cardano-ignite-base
ARG TESTNET_BUILDER_IMAGE=scratch
ARG HASKELL_BUILDER_IMAGE=scratch

FROM ${HASKELL_BUILDER_IMAGE} AS build

# NOTE:
# Additional ARG definitions can be found further below in the Dockerfile.

# cardano-cli

ARG CARDANO_CLI_VERSION="11.0.0.0"

WORKDIR /usr/local/src
RUN git init cardano-cli

WORKDIR /usr/local/src/cardano-cli
RUN git fetch --depth 1 https://github.com/IntersectMBO/cardano-cli.git cardano-cli-${CARDANO_CLI_VERSION} && \
    git checkout FETCH_HEAD && \
    git submodule update --init --recursive
RUN echo "package *\n\
  ghc-options: +RTS -A128m -n2m -RTS\n\
\n\
jobs: \$ncpus\n\
semaphore: True" > /usr/local/src/cardano-cli/cabal.project.local

WORKDIR /usr/local/src/cardano-cli/cardano-cli

RUN cabal update && \
    cabal install exe:cardano-cli --disable-test --install-method=copy \
      --installdir=/usr/local/bin --overwrite-policy=always

# cardano-node

ARG CARDANO_NODE_REF="11.0.1"
ARG CARDANO_NODE_REPO="https://github.com/IntersectMBO/cardano-node.git"
ARG PROFILING
ENV PROFILING=${PROFILING}

WORKDIR /usr/local/src
RUN git init cardano-node

WORKDIR /usr/local/src/cardano-node
RUN git fetch --depth 1 ${CARDANO_NODE_REPO} ${CARDANO_NODE_REF} && \
    git checkout FETCH_HEAD && \
    git submodule update --init --recursive
RUN echo "package *\n\
  ghc-options: +RTS -A128m -n2m -RTS\n\
\n\
package ouroboros-network\n\
  ghc-options: -fno-ignore-asserts\n\
\n\
package ouroboros-network-framework\n\
  ghc-options: -fno-ignore-asserts\n\
\n\
package ouroboros-network-api\n\
  ghc-options: -fno-ignore-asserts\n\
\n\
package ouroboros-network-protocols\n\
  ghc-options: -fno-ignore-asserts\n\
\n\
package network-mux\n\
  ghc-options: -fno-ignore-asserts\n\
\n\
jobs: \$ncpus\n\
semaphore: True" > /usr/local/src/cardano-node/cabal.project.local

WORKDIR /usr/local/src/cardano-node/cardano-node

RUN cabal update && \
    extra_flags="" && \
    if [ "${PROFILING:-}" = "1" ]; then \
      extra_flags="${extra_flags} --enable-profiling"; \
      printf '\npackage *\n  profiling: True\n  profiling-detail: all-functions\n' \
        >> /usr/local/src/cardano-node/cabal.project.local; \
    fi && \
    cabal install exe:cardano-node --disable-test ${extra_flags} --install-method=copy \
      --installdir=/usr/local/bin --overwrite-policy=always

# tx-generator

RUN cabal install exe:tx-generator --disable-test --install-method=copy \
      --installdir=/usr/local/bin --overwrite-policy=always

FROM ${TESTNET_BUILDER_IMAGE} AS testnet_builder

#---------------------------------------------------------------------

FROM ${BASE_IMAGE} AS main

ENV CARDANO_NODE_SOCKET_PATH="/opt/cardano-node/data/db/node.socket"

ENV TZ="UTC"
RUN ln -snf /usr/share/zoneinfo/${TZ} /etc/localtime && \
    echo ${TZ} > /etc/timezone

RUN apt update && \
    apt install -y --no-install-recommends \
        doas \
        libsnappy1v5 \
        liburing2 \
        locales \
        postgresql-client && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i 's/^# *en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# libsodium

COPY --from=build --chown=root:root /usr/local/lib/libsodium.so /usr/local/lib
RUN ln -snf /usr/local/lib/libsodium.so /usr/local/lib/libsodium.so.23 && \
    ln -snf /usr/local/lib/libsodium.so /usr/local/lib/libsodium.so.23.3.0
RUN ldconfig

# secp256k1

COPY --from=build --chown=root:root /usr/lib/libsecp256k1.so* /usr/local/lib/
RUN ldconfig

# cardano-cli

COPY --from=build --chown=root:root /usr/local/bin/cardano-cli /usr/local/bin/cardano-cli

# cardano-node

COPY --from=build --chown=root:root /usr/local/bin/cardano-node /usr/local/bin/cardano-node

# tx-generator

COPY --from=build --chown=root:root /usr/local/bin/tx-generator /usr/local/bin/tx-generator

# user and group
RUN groupadd --gid 10000 cardano && \
    useradd --comment 'cardano' --create-home --gid 10000 --password '!' --shell '/bin/bash' --uid 10000 cardano

# cardano-node

RUN install --directory --owner=root --group=root --mode=0755 /opt/cardano-node && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/config && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/data && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/data/db && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/log && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/cardano-node/pools && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/tx-generator/data && \
    install --directory --owner=cardano --group=cardano --mode=0750 /opt/tx-generator/scripts-fallback/

COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/pools /opt/cardano-node/pools
COPY --from=testnet_builder --chown=cardano:cardano /tmp/testnet/utxos /opt/cardano-node/utxos

# tx-generator

COPY --from=build --chown=cardano:cardano /usr/local/src/cardano-node/bench/tx-generator/data/*.json /opt/tx-generator/data
COPY --from=build --chown=cardano:cardano /usr/local/src/cardano-node/bench/tx-generator/scripts-fallback/*.plutus /opt/tx-generator/scripts-fallback/

# Permit cardano user to run commands 'ip' and 'tc' as root
RUN echo 'permit setenv { PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin } :cardano' >> /etc/doas.conf
RUN echo 'permit nopass cardano as root cmd ip' >> /etc/doas.conf
RUN echo 'permit nopass cardano as root cmd tc' >> /etc/doas.conf

COPY cardano-node/scripts/*.sh /
COPY scripts/node_routes.sh /
RUN chmod 0755 /*.sh

COPY cardano-node/cmd.sh /
RUN chmod 0755 /cmd.sh

USER cardano

CMD ["/cmd.sh"]
